version: '3.8'

services:
  booklibrary.api:
    image: ${DOCKER_REGISTRY-}booklibraryapi
    container_name: BookLibrary.Api
    build:
      context: .
      dockerfile: src/BookLibrary.Api/Dockerfile
    depends_on:
      - my-posgresql-db
    networks:
      - shared-net
  
  my-posgresql-db:
    image: postgres:latest
    container_name: BookLibrary.Db
    environment:
      - POSTGRES_DB=BookLibraryDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /e/docker-volumes/booklibrary-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - shared-net

  my-seq:
    image: datalust/seq:latest
    container_name: BookLibrary.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=12345678
    ports:
      - 5341:5341
      - 8081:80
    networks:
      - shared-net

  my-redis:
    image: redis:latest
    container_name: BookLibrary.Redis
    restart: always
    networks:
      - shared-net

networks:
  shared-net:
    external: true   

